# Generated by Django 4.2.20 on 2025-09-04 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assunto",
            options={"ordering": ["nome", "conteudo"]},
        ),
        migrations.AlterModelOptions(
            name="conteudo",
            options={"ordering": ["nome", "materia"]},
        ),
        migrations.AlterModelOptions(
            name="materia",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="pessoa",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="questao",
            options={"ordering": ["assunto"]},
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="email",
        ),
        migrations.AddField(
            model_name="assunto",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conteudo",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materia",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pessoa",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pessoa",
            name="usuario",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pessoa",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="nome",
            field=models.CharField(
                help_text="Digite seu nome completo",
                max_length=50,
                verbose_name="Qual o seu nome?",
            ),
        ),
        migrations.CreateModel(
            name="Servidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siape", models.CharField(max_length=50)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servidor",
                        to="paginas.pessoa",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servidor_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pessoa__nome", "siape"],
            },
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=50)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno",
                        to="paginas.pessoa",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pessoa__nome", "matricula"],
            },
        ),
    ]
